### ISSUE TITLE
Investigate pandoc error handling

### ISSUE THREAD

**Issue by vrom911** [kowainik/hakyll-shortcut-links#6]

**Comment by chshersh** [comment]
It looks like that for the purpose of error reporting instead of `pandocCompilierWithTransform` we can use [`pandocCompilerWithTransformM`](https://hackage.haskell.org/package/hakyll-4.12.5.1/docs/Hakyll-Web-Pandoc.html#v:pandocCompilerWithTransformM) which has the following type:

```haskell
pandocCompilerWithTransformM :: ReaderOptions -> WriterOptions -> (Pandoc -> Compiler Pandoc) -> Compiler (Item String)
```

It work with the `Compiler` monad. But I see that this monad implements the following instance:

```haskell
MonadError [String] Compiler
```

So, if we just change the type of `applyShortcuts` function to:

```haskell
applyAllShortcuts :: MonadError [String] m => Pandoc.Pandoc -> m Pandoc.Pandoc
```

We should be able to throw errors using the `throwError` function. I'm not sure, what to with warnings though. `Compiler` doesn't support distinction between errors and warnings.
